### PR TITLE
Update contrailvif.py

### PR DESCRIPTION
**Pull request by upadhyay-prashant**
adding variable to get full config instead of just base config.

### CODE REVIEW

**Comment by gdpak** [comment]
@MayankGo Can you please review this code ?

**Comment by MayankGo** [comment]
looks fine to me.. please go ahead and merge..

**Comment by gdpak** [comment]
Actually code is reading virt_type from nova config - nova.libvirt.virt_type in case it is None.
In code below only virt_type which makes difference in returned values is 'lxc'
so most probably nova code is calling this code with virt_type as 'lxc'.

So please try setting virt_type as 'lxc' instead of 'qemu' and you should see same result ?
We can avoid packaging and other hassles..

**Comment by upadhyay-prashant** [comment]
gdpak please make me understand how does value of virt_type is an issue here. What I have changed is just calling the function with right arguments . 

def get_config(self, instance, vif, image_meta,
                   inst_type, virt_type):

above is the function definition and not

def get_config(self, instance, vif, image_meta,
                   inst_type):

**Comment by gdpak** [comment]
I was trying to say virt_type can also be read in libvirt based on nova config file as described in https://wiki.openstack.org/wiki/LibvirtVIFDrivers. Also as matter of fact, get_config implementation of libvirt also has one additional parameter 'host' so there are many overloaded definition of get_config. hard to say which one is correct.
Anyway Mayank and myself spoke on this and it seems ok to make this change also. So we will merge this code.

**Pull request merged**
